# Generated by Django 5.2 on 2025-04-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_id_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('non_fiction', 'Non Fiction'), ('mystery', 'Mystery'), ('children', 'Children Book'), ('sci_fi', 'Science Fiction'), ('biography', 'Biography')], max_length=20),
        ),
    ]
